

---


-  hosts: all
   tags: always
   become: yes

   roles: 
      - all_servers


-  hosts: web_servers
   become: yes

   roles:
      - websr


-   hosts: db_servers
    become: yes

    roles:
       - dbser  
